# This is a basic workflow to help you get started with Actions

name: CI

on:
  pull_request:
    types: [opened, closed, reopened, synchronized, edited]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  printJob:    
    name: Print event
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github.event) }}
      run: |
        echo "$GITHUB_CONTEXT"
